name: PHPUnit Tests

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-cache:
    runs-on: ubuntu-latest
    name: Build Cache

    steps:
      - uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer-cache
        working-directory: ./core
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('./api/composer.lock') }}-${{ hashFiles('./core/composer.lock') }}

      - name: Setup PHP
        if: steps.cache.outputs.cache-hit != 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer:v1

      - name: Install dependencies (core)
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./core
        run: composer install

      - name: Install dependencies (api)
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./api
        run: composer install

  phpunitCore:
    name: PHPUnit (Core)
    needs: build-cache

    uses: christopher-learningpool/github-actions/.github/workflows/workflow_unit.yml@unit-coverage-report
    with:
      directory: core
      testsuites: '["Project-Test-Suite"]'
      coverage: true

  phpunitAPI:
    name: PHPUnit (API)
    needs: build-cache

    uses: christopher-learningpool/github-actions/.github/workflows/workflow_unit.yml@unit-coverage-report
    with:
      directory: api
      testsuites: '["api-testsuite-1","api-testsuite-2"]'
      coverage: true

  coverage-report:
    name: Coverage Reporting
    needs: [phpunitCore, phpunitAPI]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: mkdir coveragetmp

      - uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: ./coveragetmp

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v1

      - working-directory: ./coveragetmp
        run: composer require --dev phpunit/phpcov

      - working-directory: ./coveragetmp
        run: ./vendor/bin/phpcov merge --clover ./clover.xml ./coveragetmp/

      - name: Upload full coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./clover.xml
