name: PHPUnit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}


jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [core, api]

    steps:
    - uses: actions/checkout@v2
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('./api/composer.lock') }}-${{ hashFiles('./core/composer.lock') }}

    - name: Install ${{ matrix.directory }} dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      uses: php-actions/composer@v6
      with:
        php_version: "7.4"
        working_dir: ./${{ matrix.directory }}

    - name: PHPUnit/${{ matrix.directory }}
      uses: php-actions/composer@v6
        with:
          php_version: "7.4"
          working_dir: ./${{ matrix.directory }}

    - name: PHPUnit/${{ matrix.directory }}
      uses: php-actions/phpunit@v3
      with:
        php_version: "7.4"
        configuration: ./${{ matrix.directory }}/phpunit.xml