name: PHPUnit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}


jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [core, api]

    steps:
    - uses: actions/checkout@v2

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: pcov
        tools: composer:v2

    - name: Install dependencies for ${{ matrix.directory }}
      run: |
        cd ./${{ matrix.directory }}
        composer install

    - name: Run PHPUnit tests
      run: |
        cd ./${{ matrix.directory }}
        vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Send code coverage report to Codecov.io
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}