name: PHPUnit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}


jobs:
  matrix:
    name: Build Matrix
    runs-on: ubuntu-latest

    outputs:
      apiSuite: ${{ steps.execAPI.outputs.matrix }}
      coreSuite: ${{ steps.execCORE.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer-cache
        working-directory: ./api
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Bit of a hardcode.
          key: ${{ runner.os }}-${{ hashFiles('./api/composer.lock') }}-${{ hashFiles('./core/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v1
    # API Suites
      - working-directory: ./api
        run: composer install

      - working-directory: ./api
        id: execAPI
        run: echo "::set-output name=matrix::$(vendor/bin/phpunit --list-suites | sed -ne '/Available test suite(s):/,$p' | sed '1d' | sed 's/ - //g' | jq -R -s -c 'split("\n")[:-1]') | jq tostring"
    # CORE Suites
      - working-directory: ./core
        run: composer install

      - working-directory: ./core
        id: execCORE
        run: echo "::set-output name=matrix::$(vendor/bin/phpunit --list-suites | sed -ne '/Available test suite(s):/,$p' | sed '1d' | sed 's/ - //g' | jq -R -s -c 'split("\n")[:-1]') | jq tostring"

  phpunitCore:
    name: PHPUnit (Core)
    needs: matrix

    uses: christopher-learningpool/github-actions/.github/workflows/workflow_unit.yml@github-actions-unit
    with:
      directory: core
      testsuites: ${{ needs.matrix.outputs.coreSuite }}

  phpunitAPI:
    name: PHPUnit (API)
    needs: matrix

    uses: christopher-learningpool/github-actions/.github/workflows/workflow_unit.yml@github-actions-unit
    with:
      directory: api
      testsuites: ${{ needs.matrix.outputs.apiSuite }}