name: PHPUnit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}


jobs:
  matrix_core:
    name: Generate PHPUnit (core) testing matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.core-testsuites.outputs.matrix}}
    steps:
      - uses: actions/checkout@v2

      - name: List of Testsuites
        id: core-testsuites
        working-directory: ./core
        run: echo "::set-output name=dir::$(vendor/bin/phpunit --list-suites | sed -ne '/Available test suite(s):/,$p' | sed '1d' | sed 's|[- ,]||g' | jq -Rsc 'split("\n")' | jq '[ .[] | select(length > 0) ]')"

  matrix_api:
    name: Generate PHPUnit (api) testing matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.api-testsuites.outputs.matrix}}
    steps:
      - uses: actions/checkout@v2

      - name: List of Testsuites
        id: api-testsuites
        working-directory: ./api
        run: echo "::set-output name=dir::$(vendor/bin/phpunit --list-suites | sed -ne '/Available test suite(s):/,$p' | sed '1d' | sed 's|[- ,]||g' | jq -Rsc 'split("\n")' | jq '[ .[] | select(length > 0) ]')"

  phpunit_core:
    name: PHPUnit Core Testsuites
    runs-on: ubuntu-latest
    needs: matrix_core
    strategy:
      matrix:
        testsuite: ${{ needs.matrix_core.outputs.matrix }}

    steps:
      - uses: ./.github/workflows/workflow_unit.yml
        with:
          directory: core
          testsuite: ${{ matrix.testsuite }}

  phpunit_api:
    name: PHPUnit Core Testsuites
    runs-on: ubuntu-latest
    needs: matrix_api
    strategy:
      matrix:
        testsuite: ${{ needs.matrix_api.outputs.matrix }}

    steps:
      - uses: ./.github/workflows/workflow_unit.yml
        with:
          directory: api
          testsuite: ${{ matrix.testsuite }}