name: PHPUnit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}


jobs:
  phpunit:
    name: PHPUnit (${{ matrix.directory }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: [core, api]

    steps:
      - uses: ./.github/workflows/workflow_unit.yml
        with:
          directory: ${{ matrix.directory }}