on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      testsuite:
        required: true
        type: string

jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: PHPUnit (${{ inputs.directory }}) Testsuite (${{ inputs.testsuite  }})

    steps:
      - uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Bit of a hardcode.
          key: ${{ runner.os }}-${{ hashFiles('./api/composer.lock') }}-${{ hashFiles('./core/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v1

      - name: Install dependencies for ${{ inputs.directory }}
        working-directory: ./${{ inputs.directory }}
        run: composer install

      - name: Run PHPUnit testsuite
        working-directory: ./${{ inputs.directory }}
        run: vendor/bin/phpunit --testsuite ${{ inputs.testsuite  }}